title: "Gerivan's personal portfolio"
description: "Building secure tools with open source."
theme: jekyll-theme-minimal
include: [".nojekyll", "*.html", "*.ico", "*.png", "*.json", "_headers", "CNAME"]
exclude: []  # Remove as exclusões já que os READMEs estão renomeados
plugins:
  - jekyll-sitemap
