title: "Gerivan's personal portfolio"
description: "Building secure tools with open source."
theme: jekyll-theme-minimal
include: [".nojekyll", "*.html", "*.md", "*index.html", "docs/"]
exclude: ["README.md", "README.pt.md"]
plugins:
  - jekyll-sitemap
